#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend  mariacelin_frontend
        bind *:80
        mode http
        default_backend mariacelin_backend 
backend	maricelin_backend
        balance roundrobin
        server 414104-web-01 52.201.222.70:80 check
        server 414104-web-02 34.239.253.80:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
